### ISSUE TITLE
bundle-sfx doesn't product proper bundle when sass is included

### ISSUE THREAD

**Issue by gsong** [theefer/plugin-sass#10]
Everything works fine in development mode, and in regular bundle, but when using SFX bundles, SystemJS isn't initialized properly when this plugin is included. If I remove this plugin, then everything works again.

**Comment by iranreyes** [comment]
Yes, this happened to me too. My workaround was modify the build file.

**Comment by mgamsjager** [comment]
@iranreyes  and what did you change?

bundle issue I have is more path related because I use @import in my scss and the path varies from browser to jspm bundle by the looks ofit

**Comment by Cybermage83** [comment]
@iranreyes I am also interested to find out. What did you do to make it work. Thanks

**Comment by jarrodmedrano** [comment]
I've added a pull request for this issue.

https://github.com/theefer/plugin-sass/pull/12
