### ISSUE TITLE
"ws" dependency not in sass.js package.json but required to bundle

### ISSUE THREAD

**Issue by theefer** [theefer/plugin-sass#2]
See https://github.com/medialize/sass.js/issues/34.

Prevents proper bundling without manually installing `"ws"` and hooking it as a dependency of "sass.js". Should be possible to add as an override, but hoping to get it added inside the upstream `package.json` instead.

**Comment by theefer** [comment]
This seems to be in a code path that is never meant to be called, and it just a side-effect of SystemJS trying to pre-load the whole dependency tree. /cc @guybedford

I think the fix here would better be fixed using a custom override for sass.js that declares a dep on libsass.js.mem. Unfortunately doing so raises another issue:

```
     Error evaluating file:/tmp/test2/jspm_packages/npm/sass.js@0.9.2.js
     Error evaluating file:/tmp/test2/jspm_packages/npm/sass.js@0.9.2/dist/sass.sync.js
     ENOENT, no such file or directory 'test2/jspm_packages/npm/sass.js@0.9.2/dist/libsass.js.mem'
         at Object.fs.openSync (fs.js:438:18)
         at Object.fs.readFileSync (fs.js:289:15)
         at Object.read (evalmachine.<anonymous>:72:41)
         at Object.readBinary (evalmachine.<anonymous>:82:30)
         at evalmachine.<anonymous>:264823:40
         at evalmachine.<anonymous>:9:24
         at evalmachine.<anonymous>:13:4
         at Object.<anonymous> (evalmachine.<anonymous>:265485:3)
         at evalmachine.<anonymous>:265487:4
         at doEval (/home/seb/.nvm/v0.10.33/lib/node_modules/jspm/node_modules/systemjs/dist/system.src.js:2400:10)
```

This is seemingly due to the way the location of that file is detected, using `__dirname` in Node which doesn't seem to quite result in the right path (it works fine in the browser).

**Comment by guybedford** [comment]
@theefer have you tried mapping `ws` to `@empty` in an override?

**Comment by theefer** [comment]
I have now tried to run an isolated test case where I do:

```
$ jspm install sass.js -o '{map: {ws: "@empty"}}'
```

This correctly records the override in `package.json`:

``` json
   ...
    "overrides": {
      "npm:sass.js@0.9.2": {
        "map": {
          "ws": "@empty"
        }
      }
    }
```

However it doesn't seem to write it to `config.js`?

``` js
System.config({
    "sass.js": "npm:sass.js@0.9.2",
   // ...
    "npm:sass.js@0.9.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.1"
    },
    // ...
```

Is this a bug or am I doing something wrong?

Adding a `"ws": "@empty"` mapping to the config manually does solve the issue with loading `ws` and fixes the plugin for bundling (yay!), so I will open a PR to add that override to the registry and hopefully _that_ will get properly applied.

**Comment by theefer** [comment]
Sadly applying the override in the registry still doesn't make it apply in my local config. Might still be doing something wrong :cry:

**Comment by theefer** [comment]
Interestingly, once I manually patch the config.js file, the bundle works fine with jspm 0.16 but _not_ with jspm 0.15, which seems to return a wrong `__dirname` (returns something like `/seb/work/jspm-dev/test-sass-plugin/` where it should be `/home/seb/work/jspm-dev/test-sass-plugin/`).

**Comment by guybedford** [comment]
@theefer yes that was something that has been fixed in SystemJS along with the jspm beta.

The map won't show up in the config, but it should apply by rewriting inside of the requires in the code when installing. Would be interesting to see why that isn't working. Are you disabling the node conversion perhaps?

**Comment by theefer** [comment]
> Are you disabling the node conversion perhaps?

I don't know how I would do that, so I guess I am not? :-)

So I can see the map being applied in `jspm_packages/npm/sass.js@0.9.2/.jspm.json`:

``` json
  "dist": {
    "shasum": "c9f1e0f6448059ab0f57c161c24cada1e8f419cd",
    "tarball": "http://registry.npmjs.org/sass.js/-/sass.js-0.9.2.tgz"
  },
  "jspm": {
    "map": {
      "ws": "@empty"
    }
  },
  "map": {
    "ws": "@empty"
  },
  "format": "cjs",
```

and also in `sass.worker.js`:

```
jspm_packages/npm/sass.js@0.9.2 $ grep -R @empty
dist/sass.worker.js:            var WebSocket = ENVIRONMENT_IS_NODE ? require('@empty') : window["WebSocket"];
dist/sass.worker.js:        var WebSocketServer = require('@empty').Server;
```

However it wasn't applied to `sass.sync.js`:

```
jspm_packages/npm/sass.js@0.9.2 $ grep -R '"ws"'
dist/sass.sync.js:              var WebSocket = ENVIRONMENT_IS_NODE ? require("ws") : window["WebSocket"];
dist/sass.sync.js:          var WebSocketServer = require("ws").Server;
```

In case it is related, `sass.sync.js` is the main file:

```
jspm_packages/npm/sass.js@0.9.2 $ grep '"main"' .jspm.json 
  "main": "./dist/sass.sync.js",
```

**Comment by guybedford** [comment]
That's really strange, could be a bug of some sort. Will test this out my side when I have time to debug (later this week when I'm back).

**Comment by guybedford** [comment]
I've just done some more debugging here, it seems this is some kind of Traceur error parsing the source of sass.worker.js. I've posted https://github.com/systemjs/builder/issues/221.

**Comment by guybedford** [comment]
@theefer I finally managed to fix this in https://github.com/jspm/jspm-cli/commit/33bd8786dfaaf74661b52310ccdda7dbf1fc9953. It was suitably obscure and nothing to do with the parsing. Hoping to post an updated beta very soon.

**Comment by theefer** [comment]
@guybedford Great, I'll try it out again as soon as the new beta is out, thanks!

**Comment by brettstack** [comment]
Is this the last blocking issue before this can be used?

**Comment by theefer** [comment]
@breandr This is needed to be able to bundle sass files, yes. I've just fixed the other bug that was preventing dynamic usage (compile in browser), so that should work now. There are likely lots of bugs in more advanced features such as `@import` etc, but at least we can start working on that now!

**Comment by theefer** [comment]
This is now fixed with latest JSPM beta and basic bundling now works!
